### ISSUE TITLE
Can't install the package on symfony 5.

### ISSUE THREAD

**Issue by lotiko** [netzmacht/php-leaflet#7]
Hello my project is on symfony 5 and the package can't be install because of that:
"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for netzmacht/php-leaflet ^1.1 -> satisfiable by netzmacht/php-leaflet[1.1.0].
    - netzmacht/php-leaflet 1.1.0 requires symfony/event-dispatcher ^2.3 || ^3.0 || ^4.0 -> no matching package found.
"
The versions of symfony/event-dispatcher is 5.0 now, somebody know if i can downgrade my versions with no probleme or if your package can work on versions 5 of event-dispatcher.
Sincerly

**Comment by dmolineus** [comment]
At the moment the context there I use this libary depends on symfony 4. As ` symfony/event-dispatcher` includes a BC break and providing support for both v4 and v5 isn't trivial, this hasn't a high priority for me. 

It has to be fixed in https://github.com/netzmacht/php-javascript-builder first.

Feel free to provide a PR.
